# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Cloudtasker::Testing; end
class RSpec::Core::Formatters::BaseTextFormatter; end
